name: ESPFlyController

options:
  bundleIdPrefix: com.miochili
  deploymentTarget:
    iOS: "15.0"

targets:
  ESPFlyController:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - .git/**
          - .github/**
          - README.md
          - codemagic.yaml
          - project.yml
          - build.yml
    resources:
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.miochili.ESPFlyController
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: 1
