targets:
  ESPFlyController:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - .git/**
          - .github/**
          - README.md
          - codemagic.yaml
          - project.yml
          - Assets.xcassets/**
    resources:
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.miochili.ESPFlyController
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: 1
